"""
Django settings for django_two project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

"""
BASE_DIR just finds the project path with
../../ (relative to settings.py)

Note that the directory this python file is executed from is
../ (relative to settings.py)

with open("ho.txt", "w") as f:
    f.write(__file__)
    f.write("\n")
    f.write(os.path.abspath(__file__))
    f.write("\n")
    f.write(os.path.dirname(os.path.abspath(__file__)))
    f.write("\n")
    f.write(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    f.write("\n")
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    # These are all apps some of which have their own models!
    # That's why you need the initial migrate!
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # Allows django to find static files
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_two.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        # Django Templates + APP_DIRS True tells Django to look at the
        # templates directory within each app directory like
        # polls/templates/polls/base.html
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_two.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

VALIDATION_BASE = 'django.contrib.auth.password_validation.'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': VALIDATION_BASE + 'UserAttributeSimilarityValidator',
    },
    {
        'NAME': VALIDATION_BASE + 'MinimumLengthValidator',
    },
    {
        'NAME': VALIDATION_BASE + 'CommonPasswordValidator',
    },
    {
        'NAME': VALIDATION_BASE + 'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# This is default! We just added it to explicate
STATICFILES_FINDERS = [
    # FileSysFinder searches directories in STATICFILES_DIRS
    'django.contrib.staticfiles.finders.FileSystemFinder',
    # AppDirsFinder searches the 'static' directory within each app directory
    # like polls/static/polls/style.css
    # Note that you don't need the inner polls directory but we have it
    # to differenciate 'style.css' for different apps - like a namespace
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

SECRET_KEY = None
try:
    from . import secret
except ImportError:
    raise Exception("Error importing secret.py from settings.py. " +
                    "Inquire to itsnamgyu@gmail.com for secret file")

if SECRET_KEY is None:
    raise Exception("SECRET_KEY is not set. " +
                    "Inquire to itsnamgyu@gmail.com for secret file")

DEBUG = True
ALLOWED_HOSTS = ['*']
